on:
  pull_request:
  push:
  schedule:
    - cron: '0 0 3 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build container
      run: |
        docker build . --file Dockerfile 
